/*******************************************************************************
* Copyright 2019-2021 Intel Corporation
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cpu/loongarch64/jit_generator.hpp"

#include "cpu/loongarch64/gemm/f32/common_f32.hpp"

namespace dnnl {
namespace impl {
namespace cpu {
namespace loongarch64 {

jit_lasx_f32_copy_at_kern::jit_lasx_f32_copy_at_kern()
    : jit_generator(nullptr, F32_COPY_KERNEL_CODE_SIZE) {}

void jit_lasx_f32_copy_at_kern::generate() {

#define M a0//rdi
#define N a1//rsi
#define A a2//rdx
#define LDA a3//rcx
#define ALPHA a4//r8
#define B a5//r9

#define I t4//rax
#define A1 t5//r10
#define A2 a4//r8
#define LDA3 t6//r11
#define TM s1
#define TM0 s0
#define LDA2 t7
#define LDA4 t8

    inLocalLabel();
    {
        std::vector<Xbyak_loongarch64::Label> labels(95);

        preamble();

        ld_d(M, M, 0);
        ld_d(N, N, 0);
        ld_d(LDA, LDA, 0);
        addi_d(B, B, 128);
        slli_d(LDA, LDA, 0x2);
        add_d(LDA2, LDA, LDA);
        add_d(LDA3, LDA2, LDA);
        add_d(LDA4, LDA3, LDA);
        xvldrepl_w(xr6, ALPHA, 0);
        vseq_b(vr3, vr3, vr3);
        vsrli_w(vr3, vr3, 0x17);
        vslli_w(vr3, vr3, 0x19);
        vsrli_w(vr3, vr3, 0x2);
        vseq_b(vr4, vr4, vr4);
        vslli_w(vr4, vr4, 0x1f);
        xvpermi_q(xr4, xr4, 0x20);
        vfcmp_cle_s(vr31, vr3, vr6);
        vpickve2gr_w(TM, vr31, 0);
        bnez(TM, labels[90]);
        mov_imm(TM, 0x18);
        blt(N, TM, labels[62]);

        L(labels[64]);
        add_d(A1, A, zero);
        mov_imm(TM, 0x18);
        mul_d(I, LDA, TM);
        add_d(A, A, I);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[50]);

        L(labels[67]);
        vld(vr0, A1, 0);
        vldx(vr4, A1, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A1, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x20);
        xvst(xr2, B, 0x40);
        xvst(xr3, B, 0xa0);
        vld(vr0, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvst(xr0, B, -0x60);
        xvst(xr1, B, 0);
        xvst(xr2, B, 0x60);
        xvst(xr3, B, 0xc0);
        vld(vr0, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvst(xr0, B, -0x40);
        xvst(xr1, B, 0x20);
        xvst(xr2, B, 0x80);
        xvst(xr3, B, 0xe0);
        addi_d(A1, A1, 16);
        addi_d(B, B, 384);
        addi_d(I, I, -1);
        blt(zero, I, labels[67]);

        L(labels[50]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[60]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        ldx_d(TM0, A1, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A1, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A1, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x20);
        vld(vr0, A2, 0);
        vldx(vr1, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A2, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvst(xr0, B, -0x60);
        xvst(xr1, B, 0);
        vld(vr0, A2, 0);
        vldx(vr1, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A2, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvst(xr0, B, -0x40);
        xvst(xr1, B, 0x20);
        addi_d(A1, A1, 8);
        addi_d(B, B, 192);

        L(labels[60]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[61]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A1, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A1, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A1, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvst(xr0, B, -0x80);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvst(xr0, B, -0x60);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvst(xr0, B, -0x40);
        add_d(A2, A2, LDA4);
        addi_d(A1, A1, 4);
        addi_d(B, B, 96);

        L(labels[61]);
        addi_d(N, N, -0x18);
        mov_imm(TM, 0x18);
        bge(N, TM, labels[64]);

        L(labels[62]);
        mov_imm(TM, 0x10);
        blt(N, TM, labels[69]);
        add_d(A1, A, zero);
        slli_d(I, LDA, 4);
        add_d(A, A, I);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[65]);

        L(labels[63]);
        vld(vr0, A1, 0);
        vldx(vr4, A1, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A1, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr2, xr3, xr5);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x40);
        xvst(xr2, B, 0);
        xvst(xr3, B, 0x40);
        vld(vr0, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvst(xr0, B, -0x60);
        xvst(xr1, B, -0x20);
        xvst(xr2, B, 0x20);
        xvst(xr3, B, 0x60);
        addi_d(A1, A1, 16);
        addi_d(B, B, 256);
        addi_d(I, I, -1);
        blt(zero, I, labels[63]);

        L(labels[65]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[66]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        ldx_d(TM0, A1, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A1, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A1, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x40);
        vld(vr0, A2, 0);
        vldx(vr1, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A2, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvst(xr0, B, -0x60);
        xvst(xr1, B, -0x20);
        addi_d(A1, A1, 8);
        addi_d(B, B, 128);

        L(labels[66]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[68]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A1, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A1, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A1, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvst(xr0, B, -0x80);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvst(xr0, B, -0x60);
        add_d(A2, A2, LDA4);
        addi_d(A1, A1, 4);
        addi_d(B, B, 64);

        L(labels[68]);
        addi_d(N, N, -0x10);

        L(labels[69]);
        mov_imm(TM, 0x8);
        blt(N, TM, labels[74]);
        add_d(A1, A, zero);
        slli_d(I, LDA, 3);
        add_d(A, A, I);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[71]);

        L(labels[70]);
        vld(vr0, A1, 0);
        vldx(vr4, A1, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A1, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x60);
        xvst(xr2, B, -0x40);
        xvst(xr3, B, -0x20);
        addi_d(A1, A1, 16);
        addi_d(B, B, 128);
        addi_d(I, I, -1);
        blt(zero, I, labels[70]);

        L(labels[71]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[72]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        ldx_d(TM0, A1, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A1, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A1, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x60);
        addi_d(A1, A1, 8);
        addi_d(B, B, 64);

        L(labels[72]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[73]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A1, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A1, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A1, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvst(xr0, B, -0x80);
        add_d(A2, A2, LDA4);
        addi_d(A1, A1, 4);
        addi_d(B, B, 32);

        L(labels[73]);
        addi_d(N, N, -0x8);

        L(labels[74]);
        mov_imm(TM, 0x4);
        blt(N, TM, labels[79]);
        add_d(A1, A, zero);
        add_d(A, A, LDA4);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[76]);

        L(labels[75]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        vldx(vr2, A1, LDA2);
        vldx(vr3, A1, LDA3);
        vilvl_w(vr4, vr1, vr0);
        vilvh_w(vr5, vr1, vr0);
        vilvl_w(vr1, vr3, vr2);
        vilvh_w(vr3, vr3, vr2);
        vilvl_d(vr0, vr1, vr4);
        vilvh_d(vr1, vr1, vr4);
        vilvl_d(vr2, vr3, vr5);
        vilvh_d(vr3, vr3, vr5);
        vst(vr0, B, -0x80);
        vst(vr1, B, -0x70);
        vst(vr2, B, -0x60);
        vst(vr3, B, -0x50);
        add_d(A2, A1, LDA4);
        addi_d(A1, A1, 16);
        addi_d(B, B, 64);
        addi_d(I, I, -1);
        blt(zero, I, labels[75]);

        L(labels[76]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[77]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        ldx_d(TM0, A1, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A1, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        vilvl_w(vr4, vr1, vr0);
        vilvh_w(vr1, vr1, vr0);
        vilvl_d(vr0, vr1, vr4);
        vilvh_d(vr1, vr1, vr4);
        vst(vr0, B, -0x80);
        vst(vr1, B, -0x70);
        add_d(A2, A1, LDA4);
        addi_d(A1, A1, 8);
        addi_d(B, B, 32);

        L(labels[77]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[78]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A1, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A1, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        vst(vr0, B, -0x80);
        add_d(A2, A1, LDA4);
        addi_d(A1, A1, 4);
        addi_d(B, B, 16);

        L(labels[78]);
        addi_d(N, N, -0x4);

        L(labels[79]);
        mov_imm(TM, 0x2);
        blt(N, TM, labels[84]);
        add_d(A1, A, zero);
        add_d(A, A, LDA2);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[81]);

        L(labels[80]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        vilvl_w(vr4, vr1, vr0);
        vilvh_w(vr1, vr1, vr0);
        vbsll_v(vr0, vr4, 0);
        vstelm_d(vr0, B, -0x80, 0);
        vstelm_d(vr0, B, -0x78, 1);
        vstelm_d(vr1, B, -0x70, 0);
        vstelm_d(vr1, B, -0x68, 1);
        add_d(A2, A1, LDA2);
        addi_d(A1, A1, 16);
        addi_d(B, B, 32);
        addi_d(I, I, -1);
        blt(zero, I, labels[80]);

        L(labels[81]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[82]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        vilvl_w(vr0, vr1, vr0);
        vstelm_d(vr0, B, -0x80, 0);
        vstelm_d(vr0, B, -0x78, 1);
        add_d(A2, A1, LDA2);
        addi_d(A1, A1, 8);
        addi_d(B, B, 16);

        L(labels[82]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[83]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        vstelm_d(vr0, B, -0x80, 0);
        add_d(A2, A1, LDA2);
        addi_d(A1, A1, 4);
        addi_d(B, B, 8);

        L(labels[83]);
        addi_d(N, N, -0x2);

        L(labels[84]);
        mov_imm(TM, 0x1);
        blt(N, TM, labels[89]);
        add_d(A1, A, zero);
        add_d(A, A, LDA);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[86]);

        L(labels[85]);
        vld(vr0, A1, 0);
        vstelm_w(vr0, B, -0x80, 0);
        vstelm_w(vr0, B, -0x7c, 1);
        vstelm_w(vr0, B, -0x78, 2);
        vstelm_w(vr0, B, -0x74, 3);
        add_d(A2, A1, LDA);
        addi_d(A1, A1, 16);
        addi_d(B, B, 16);
        addi_d(I, I, -1);
        blt(zero, I, labels[85]);

        L(labels[86]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[87]);
        vldrepl_d(vr0, A1, 0);
        vstelm_w(vr0, B, -0x80, 0);
        vstelm_w(vr0, B, -0x7c, 1);
        add_d(A2, A1, LDA);
        addi_d(A1, A1, 8);
        addi_d(B, B, 8);

        L(labels[87]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[88]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        vstelm_w(vr0, B, -0x80, 0);
        add_d(A2, A1, LDA);
        addi_d(A1, A1, 4);
        addi_d(B, B, 4);

        L(labels[88]);
        addi_d(N, N, -0x1);

        L(labels[89]);
        b(labels[59]);

        L(labels[90]);
        vxor_v(vr3, vr3, vr4);
        vfcmp_cle_s(vr31, vr3, vr6);
        vpickve2gr_w(TM, vr31, 0);
        bnez(TM, labels[27]);
        xvbsll_v(xr6, xr4, 0);
        mov_imm(TM, 0x18);
        blt(N, TM, labels[1]);

        L(labels[91]);
        add_d(A1, A, zero);
        mov_imm(TM, 0x18);
        mul_d(I, LDA, TM);
        add_d(A, A, I);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[93]);

        L(labels[92]);
        vld(vr0, A1, 0);
        vldx(vr4, A1, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A1, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvxor_v(xr0, xr6, xr0);
        xvxor_v(xr1, xr6, xr1);
        xvxor_v(xr2, xr6, xr2);
        xvxor_v(xr3, xr6, xr3);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x20);
        xvst(xr2, B, 0x40);
        xvst(xr3, B, 0xa0);
        vld(vr0, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvxor_v(xr0, xr6, xr0);
        xvxor_v(xr1, xr6, xr1);
        xvxor_v(xr2, xr6, xr2);
        xvxor_v(xr3, xr6, xr3);
        xvst(xr0, B, -0x60);
        xvst(xr1, B, 0);
        xvst(xr2, B, 0x60);
        xvst(xr3, B, 0xc0);
        vld(vr0, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvxor_v(xr0, xr6, xr0);
        xvxor_v(xr1, xr6, xr1);
        xvxor_v(xr2, xr6, xr2);
        xvxor_v(xr3, xr6, xr3);
        xvst(xr0, B, -0x40);
        xvst(xr1, B, 0x20);
        xvst(xr2, B, 0x80);
        xvst(xr3, B, 0xe0);
        addi_d(A1, A1, 16);
        addi_d(B, B, 384);
        addi_d(I, I, -1);
        blt(zero, I, labels[92]);

        L(labels[93]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[94]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        ldx_d(TM0, A1, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A1, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A1, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvxor_v(xr0, xr6, xr0);
        xvxor_v(xr1, xr6, xr1);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x20);
        vld(vr0, A2, 0);
        vldx(vr1, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A2, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvxor_v(xr0, xr6, xr0);
        xvxor_v(xr1, xr6, xr1);
        xvst(xr0, B, -0x60);
        xvst(xr1, B, 0);
        vld(vr0, A2, 0);
        vldx(vr1, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A2, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvxor_v(xr0, xr6, xr0);
        xvxor_v(xr1, xr6, xr1);
        xvst(xr0, B, -0x40);
        xvst(xr1, B, 0x20);
        addi_d(A1, A1, 8);
        addi_d(B, B, 192);

        L(labels[94]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[0]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A1, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A1, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A1, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvxor_v(xr0, xr6, xr0);
        xvst(xr0, B, -0x80);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvxor_v(xr0, xr6, xr0);
        xvst(xr0, B, -0x60);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvxor_v(xr0, xr6, xr0);
        xvst(xr0, B, -0x40);
        add_d(A2, A2, LDA4);
        addi_d(A1, A1, 4);
        addi_d(B, B, 96);

        L(labels[0]);
        addi_d(N, N, -0x18);
        mov_imm(TM, 0x18);
        bge(N, TM, labels[91]);

        L(labels[1]);
        mov_imm(TM, 0x10);
        blt(N, TM, labels[6]);
        add_d(A1, A, zero);
        slli_d(I, LDA, 4);
        add_d(A, A, I);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[3]);

        L(labels[2]);
        vld(vr0, A1, 0);
        vldx(vr4, A1, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A1, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvxor_v(xr0, xr6, xr0);
        xvxor_v(xr1, xr6, xr1);
        xvxor_v(xr2, xr6, xr2);
        xvxor_v(xr3, xr6, xr3);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x40);
        xvst(xr2, B, 0);
        xvst(xr3, B, 0x40);
        vld(vr0, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvxor_v(xr0, xr6, xr0);
        xvxor_v(xr1, xr6, xr1);
        xvxor_v(xr2, xr6, xr2);
        xvxor_v(xr3, xr6, xr3);
        xvst(xr0, B, -0x60);
        xvst(xr1, B, -0x20);
        xvst(xr2, B, 0x20);
        xvst(xr3, B, 0x60);
        addi_d(A1, A1, 16);
        addi_d(B, B, 256);
        addi_d(I, I, -1);
        blt(zero, I, labels[2]);

        L(labels[3]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[4]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        ldx_d(TM0, A1, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A1, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A1, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvxor_v(xr0, xr6, xr0);
        xvxor_v(xr1, xr6, xr1);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x40);
        vld(vr0, A2, 0);
        vldx(vr1, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A2, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvxor_v(xr0, xr6, xr0);
        xvxor_v(xr1, xr6, xr1);
        xvst(xr0, B, -0x60);
        xvst(xr1, B, -0x20);
        addi_d(A1, A1, 8);
        addi_d(B, B, 128);

        L(labels[4]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[5]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A1, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A1, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A1, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvxor_v(xr0, xr6, xr0);
        xvst(xr0, B, -0x80);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvxor_v(xr0, xr6, xr0);
        xvst(xr0, B, -0x60);
        add_d(A2, A2, LDA4);
        addi_d(A1, A1, 4);
        addi_d(B, B, 64);

        L(labels[5]);
        addi_d(N, N, -0x10);

        L(labels[6]);
        mov_imm(TM, 0x8);
        blt(N, TM, labels[11]);
        add_d(A1, A, zero);
        slli_d(I, LDA, 3);
        add_d(A, A, I);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[8]);

        L(labels[7]);
        vld(vr0, A1, 0);
        vldx(vr4, A1, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A1, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvxor_v(xr0, xr6, xr0);
        xvxor_v(xr1, xr6, xr1);
        xvxor_v(xr2, xr6, xr2);
        xvxor_v(xr3, xr6, xr3);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x60);
        xvst(xr2, B, -0x40);
        xvst(xr3, B, -0x20);
        addi_d(A1, A1, 16);
        addi_d(B, B, 128);
        addi_d(I, I, -1);
        blt(zero, I, labels[7]);

        L(labels[8]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[9]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        ldx_d(TM0, A1, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A1, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A1, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvxor_v(xr0, xr6, xr0);
        xvxor_v(xr1, xr6, xr1);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x60);
        addi_d(A1, A1, 8);
        addi_d(B, B, 64);

        L(labels[9]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[10]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A1, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A1, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A1, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvxor_v(xr0, xr6, xr0);
        xvst(xr0, B, -0x80);
        add_d(A2, A2, LDA4);
        addi_d(A1, A1, 4);
        addi_d(B, B, 32);

        L(labels[10]);
        addi_d(N, N, -0x8);

        L(labels[11]);
        mov_imm(TM, 0x4);
        blt(N, TM, labels[16]);
        add_d(A1, A, zero);
        add_d(A, A, LDA4);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[13]);

        L(labels[12]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        vldx(vr2, A1, LDA2);
        vldx(vr3, A1, LDA3);
        vilvl_w(vr4, vr1, vr0);
        vilvh_w(vr5, vr1, vr0);
        vilvl_w(vr1, vr3, vr2);
        vilvh_w(vr3, vr3, vr2);
        vilvl_d(vr0, vr1, vr4);
        vilvh_d(vr1, vr1, vr4);
        vilvl_d(vr2, vr3, vr5);
        vilvh_d(vr3, vr3, vr5);
        vxor_v(vr0, vr6, vr0);
        vxor_v(vr1, vr6, vr1);
        vxor_v(vr2, vr6, vr2);
        vxor_v(vr3, vr6, vr3);
        vst(vr0, B, -0x80);
        vst(vr1, B, -0x70);
        vst(vr2, B, -0x60);
        vst(vr3, B, -0x50);
        add_d(A2, A1, LDA4);
        addi_d(A1, A1, 16);
        addi_d(B, B, 64);
        addi_d(I, I, -1);
        blt(zero, I, labels[12]);

        L(labels[13]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[14]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        ldx_d(TM0, A1, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A1, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        vilvl_w(vr4, vr1, vr0);
        vilvh_w(vr1, vr1, vr0);
        vilvl_d(vr0, vr1, vr4);
        vilvh_d(vr1, vr1, vr4);
        vxor_v(vr0, vr6, vr0);
        vxor_v(vr1, vr6, vr1);
        vst(vr0, B, -0x80);
        vst(vr1, B, -0x70);
        add_d(A2, A1, LDA4);
        addi_d(A1, A1, 8);
        addi_d(B, B, 32);

        L(labels[14]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[15]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A1, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A1, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        vxor_v(vr0, vr6, vr0);
        vst(vr0, B, -0x80);
        add_d(A2, A1, LDA4);
        addi_d(A1, A1, 4);
        addi_d(B, B, 16);

        L(labels[15]);
        addi_d(N, N, -0x4);

        L(labels[16]);
        mov_imm(TM, 0x2);
        blt(N, TM, labels[21]);
        add_d(A1, A, zero);
        add_d(A, A, LDA2);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[18]);

        L(labels[17]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        vilvl_w(vr4, vr1, vr0);
        vilvh_w(vr1, vr1, vr0);
        vbsll_v(vr0, vr4, 0);
        vxor_v(vr0, vr6, vr0);
        vxor_v(vr1, vr6, vr1);
        vstelm_d(vr0, B, -0x80, 0);
        vstelm_d(vr0, B, -0x78, 1);
        vstelm_d(vr1, B, -0x70, 0);
        vstelm_d(vr1, B, -0x68, 1);
        add_d(A2, A1, LDA2);
        addi_d(A1, A1, 16);
        addi_d(B, B, 32);
        addi_d(I, I, -1);
        blt(zero, I, labels[17]);

        L(labels[18]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[19]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        vilvl_w(vr0, vr1, vr0);
        vxor_v(vr0, vr6, vr0);
        vstelm_d(vr0, B, -0x80, 0);
        vstelm_d(vr0, B, -0x78, 1);
        add_d(A2, A1, LDA2);
        addi_d(A1, A1, 8);
        addi_d(B, B, 16);

        L(labels[19]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[20]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        vxor_v(vr0, vr6, vr0);
        vstelm_d(vr0, B, -0x80, 0);
        add_d(A2, A1, LDA2);
        addi_d(A1, A1, 4);
        addi_d(B, B, 8);

        L(labels[20]);
        addi_d(N, N, -0x2);

        L(labels[21]);
        mov_imm(TM, 0x1);
        blt(N, TM, labels[26]);
        add_d(A1, A, zero);
        add_d(A, A, LDA);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[23]);

        L(labels[22]);
        vld(vr0, A1, 0);
        vxor_v(vr0, vr6, vr0);
        vstelm_w(vr0, B, -0x80, 0);
        vstelm_w(vr0, B, -0x7c, 1);
        vstelm_w(vr0, B, -0x78, 2);
        vstelm_w(vr0, B, -0x74, 3);
        add_d(A2, A1, LDA);
        addi_d(A1, A1, 16);
        addi_d(B, B, 16);
        addi_d(I, I, -1);
        blt(zero, I, labels[22]);

        L(labels[23]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[24]);
        vldrepl_d(vr0, A1, 0);
        vxor_v(vr0, vr6, vr0);
        vstelm_w(vr0, B, -0x80, 0);
        vstelm_w(vr0, B, -0x7c, 1);
        add_d(A2, A1, LDA);
        addi_d(A1, A1, 8);
        addi_d(B, B, 8);

        L(labels[24]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[25]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        vxor_v(vr0, vr6, vr0);
        vstelm_w(vr0, B, -0x80, 0);
        add_d(A2, A1, LDA);
        addi_d(A1, A1, 4);
        addi_d(B, B, 4);

        L(labels[25]);
        addi_d(N, N, -0x1);

        L(labels[26]);
        b(labels[59]);

        L(labels[27]);
        mov_imm(TM, 0x18);
        blt(N, TM, labels[33]);

        L(labels[28]);
        add_d(A1, A, zero);
        mov_imm(TM, 0x18);
        mul_d(I, LDA, TM);
        add_d(A, A, I);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[30]);

        L(labels[29]);
        vld(vr0, A1, 0);
        vldx(vr4, A1, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A1, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvfmul_s(xr0, xr6, xr0);
        xvfmul_s(xr1, xr6, xr1);
        xvfmul_s(xr2, xr6, xr2);
        xvfmul_s(xr3, xr6, xr3);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x20);
        xvst(xr2, B, 0x40);
        xvst(xr3, B, 0xa0);
        vld(vr0, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvfmul_s(xr0, xr6, xr0);
        xvfmul_s(xr1, xr6, xr1);
        xvfmul_s(xr2, xr6, xr2);
        xvfmul_s(xr3, xr6, xr3);
        xvst(xr0, B, -0x60);
        xvst(xr1, B, 0);
        xvst(xr2, B, 0x60);
        xvst(xr3, B, 0xc0);
        vld(vr0, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvfmul_s(xr0, xr6, xr0);
        xvfmul_s(xr1, xr6, xr1);
        xvfmul_s(xr2, xr6, xr2);
        xvfmul_s(xr3, xr6, xr3);
        xvst(xr0, B, -0x40);
        xvst(xr1, B, 0x20);
        xvst(xr2, B, 0x80);
        xvst(xr3, B, 0xe0);
        addi_d(A1, A1, 16);
        addi_d(B, B, 384);
        addi_d(I, I, -1);
        blt(zero, I, labels[29]);

        L(labels[30]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[31]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        ldx_d(TM0, A1, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A1, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A1, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvfmul_s(xr0, xr6, xr0);
        xvfmul_s(xr1, xr6, xr1);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x20);
        vld(vr0, A2, 0);
        vldx(vr1, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A2, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvfmul_s(xr0, xr6, xr0);
        xvfmul_s(xr1, xr6, xr1);
        xvst(xr0, B, -0x60);
        xvst(xr1, B, 0);
        vld(vr0, A2, 0);
        vldx(vr1, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A2, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvfmul_s(xr0, xr6, xr0);
        xvfmul_s(xr1, xr6, xr1);
        xvst(xr0, B, -0x40);
        xvst(xr1, B, 0x20);
        addi_d(A1, A1, 8);
        addi_d(B, B, 192);

        L(labels[31]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[32]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A1, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A1, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A1, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvfmul_s(xr0, xr6, xr0);
        xvst(xr0, B, -0x80);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvfmul_s(xr0, xr6, xr0);
        xvst(xr0, B, -0x60);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvfmul_s(xr0, xr6, xr0);
        xvst(xr0, B, -0x40);
        add_d(A2, A2, LDA4);
        addi_d(A1, A1, 4);
        addi_d(B, B, 96);

        L(labels[32]);
        addi_d(N, N, -0x18);
        mov_imm(TM, 0x18);
        bge(N, TM, labels[28]);

        L(labels[33]);
        mov_imm(TM, 0x10);
        blt(N, TM, labels[38]);
        add_d(A1, A, zero);
        slli_d(I, LDA, 4);
        add_d(A, A, I);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[35]);

        L(labels[34]);
        vld(vr0, A1, 0);
        vldx(vr4, A1, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A1, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvfmul_s(xr0, xr6, xr0);
        xvfmul_s(xr1, xr6, xr1);
        xvfmul_s(xr2, xr6, xr2);
        xvfmul_s(xr3, xr6, xr3);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x40);
        xvst(xr2, B, 0);
        xvst(xr3, B, 0x40);
        vld(vr0, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvfmul_s(xr0, xr6, xr0);
        xvfmul_s(xr1, xr6, xr1);
        xvfmul_s(xr2, xr6, xr2);
        xvfmul_s(xr3, xr6, xr3);
        xvst(xr0, B, -0x60);
        xvst(xr1, B, -0x20);
        xvst(xr2, B, 0x20);
        xvst(xr3, B, 0x60);
        addi_d(A1, A1, 16);
        addi_d(B, B, 256);
        addi_d(I, I, -1);
        blt(zero, I, labels[34]);

        L(labels[35]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[36]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        ldx_d(TM0, A1, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A1, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A1, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvfmul_s(xr0, xr6, xr0);
        xvfmul_s(xr1, xr6, xr1);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x40);
        vld(vr0, A2, 0);
        vldx(vr1, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A2, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A2, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvfmul_s(xr0, xr6, xr0);
        xvfmul_s(xr1, xr6, xr1);
        xvst(xr0, B, -0x60);
        xvst(xr1, B, -0x20);
        addi_d(A1, A1, 8);
        addi_d(B, B, 128);

        L(labels[36]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[37]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A1, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A1, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A1, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvfmul_s(xr0, xr6, xr0);
        xvst(xr0, B, -0x80);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A2, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvfmul_s(xr0, xr6, xr0);
        xvst(xr0, B, -0x60);
        add_d(A2, A2, LDA4);
        addi_d(A1, A1, 4);
        addi_d(B, B, 64);

        L(labels[37]);
        addi_d(N, N, -0x10);

        L(labels[38]);
        mov_imm(TM, 0x8);
        blt(N, TM, labels[43]);
        add_d(A1, A, zero);
        slli_d(I, LDA, 3);
        add_d(A, A, I);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[40]);

        L(labels[39]);
        vld(vr0, A1, 0);
        vldx(vr4, A1, LDA4);
        xvpermi_q(xr0, xr4, 0x02);
        add_d(A2, A1, LDA);
        vld(vr1, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr1, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr2, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr2, xr4, 0x02);
        add_d(A2, A2, LDA);
        vld(vr3, A2, 0);
        vldx(vr4, A2, LDA4);
        xvpermi_q(xr3, xr4, 0x02);
        add_d(A2, A2, LDA);
        add_d(A2, A2, LDA4);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr5, xr1, xr0);
        xvilvl_w(xr1, xr3, xr2);
        xvilvh_w(xr3, xr3, xr2);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvilvl_d(xr2, xr3, xr5);
        xvilvh_d(xr3, xr3, xr5);
        xvfmul_s(xr0, xr6, xr0);
        xvfmul_s(xr1, xr6, xr1);
        xvfmul_s(xr2, xr6, xr2);
        xvfmul_s(xr3, xr6, xr3);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x60);
        xvst(xr2, B, -0x40);
        xvst(xr3, B, -0x20);
        addi_d(A1, A1, 16);
        addi_d(B, B, 128);
        addi_d(I, I, -1);
        blt(zero, I, labels[39]);

        L(labels[40]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[41]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        ldx_d(TM0, A1, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A1, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        add_d(A2, A1, LDA4);
        vld(vr2, A2, 0);
        vldx(vr3, A2, LDA);
        ldx_d(TM0, A2, LDA2);
        vinsgr2vr_d(vr2, TM0, 1);
        ldx_d(TM0, A1, LDA3);
        vinsgr2vr_d(vr3, TM0, 1);
        add_d(A2, A2, LDA4);
        xvpermi_q(xr0, xr2, 0x02);
        xvpermi_q(xr1, xr3, 0x02);
        xvilvl_w(xr4, xr1, xr0);
        xvilvh_w(xr1, xr1, xr0);
        xvilvl_d(xr0, xr1, xr4);
        xvilvh_d(xr1, xr1, xr4);
        xvfmul_s(xr0, xr6, xr0);
        xvfmul_s(xr1, xr6, xr1);
        xvst(xr0, B, -0x80);
        xvst(xr1, B, -0x60);
        addi_d(A1, A1, 8);
        addi_d(B, B, 64);

        L(labels[41]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[42]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A1, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A1, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr4, vr2, vr0);
        add_d(A2, A1, LDA4);
        ld_w(TM0, A2, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A2, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A2, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A2, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        xvpermi_q(xr0, xr4, 0x20);
        xvfmul_s(xr0, xr6, xr0);
        xvst(xr0, B, -0x80);
        add_d(A2, A2, LDA4);
        addi_d(A1, A1, 4);
        addi_d(B, B, 32);

        L(labels[42]);
        addi_d(N, N, -0x8);

        L(labels[43]);
        mov_imm(TM, 0x4);
        blt(N, TM, labels[48]);
        add_d(A1, A, zero);
        add_d(A, A, LDA4);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[45]);

        L(labels[44]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        vldx(vr2, A1, LDA2);
        vldx(vr3, A1, LDA3);
        vilvl_w(vr4, vr1, vr0);
        vilvh_w(vr5, vr1, vr0);
        vilvl_w(vr1, vr3, vr2);
        vilvh_w(vr3, vr3, vr2);
        vilvl_d(vr0, vr1, vr4);
        vilvh_d(vr1, vr1, vr4);
        vilvl_d(vr2, vr3, vr5);
        vilvh_d(vr3, vr3, vr5);
        vfmul_s(vr0, vr6, vr0);
        vfmul_s(vr1, vr6, vr1);
        vfmul_s(vr2, vr6, vr2);
        vfmul_s(vr3, vr6, vr3);
        vst(vr0, B, -0x80);
        vst(vr1, B, -0x70);
        vst(vr2, B, -0x60);
        vst(vr3, B, -0x50);
        add_d(A2, A1, LDA4);
        addi_d(A1, A1, 16);
        addi_d(B, B, 64);
        addi_d(I, I, -1);
        blt(zero, I, labels[44]);

        L(labels[45]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[46]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        ldx_d(TM0, A1, LDA2);
        vinsgr2vr_d(vr0, TM0, 1);
        ldx_d(TM0, A1, LDA3);
        vinsgr2vr_d(vr1, TM0, 1);
        vilvl_w(vr4, vr1, vr0);
        vilvh_w(vr1, vr1, vr0);
        vilvl_d(vr0, vr1, vr4);
        vilvh_d(vr1, vr1, vr4);
        vfmul_s(vr0, vr6, vr0);
        vfmul_s(vr1, vr6, vr1);
        vst(vr0, B, -0x80);
        vst(vr1, B, -0x70);
        add_d(A2, A1, LDA4);
        addi_d(A1, A1, 8);
        addi_d(B, B, 32);

        L(labels[46]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[47]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        ldx_w(TM0, A1, LDA2);
        vinsgr2vr_w(vr2, TM0, 0);
        ldx_w(TM0, A1, LDA3);
        vinsgr2vr_w(vr3, TM0, 0);
        vilvl_w(vr2, vr3, vr2);
        vilvl_d(vr0, vr2, vr0);
        vfmul_s(vr0, vr6, vr0);
        vst(vr0, B, -0x80);
        add_d(A2, A1, LDA4);
        addi_d(A1, A1, 4);
        addi_d(B, B, 16);

        L(labels[47]);
        addi_d(N, N, -0x4);

        L(labels[48]);
        mov_imm(TM, 0x2);
        blt(N, TM, labels[54]);
        add_d(A1, A, zero);
        add_d(A, A, LDA2);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[51]);

        L(labels[49]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        vilvl_w(vr4, vr1, vr0);
        vilvh_w(vr1, vr1, vr0);
        vbsll_v(vr0, vr4, 0);
        vfmul_s(vr0, vr6, vr0);
        vfmul_s(vr1, vr6, vr1);
        vstelm_d(vr0, B, -0x80, 0);
        vstelm_d(vr0, B, -0x78, 1);
        vstelm_d(vr1, B, -0x70, 0);
        vstelm_d(vr1, B, -0x68, 1);
        add_d(A2, A1, LDA2);
        addi_d(A1, A1, 16);
        addi_d(B, B, 32);
        addi_d(I, I, -1);
        blt(zero, I, labels[49]);

        L(labels[51]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[52]);
        vld(vr0, A1, 0);
        vldx(vr1, A1, LDA);
        vilvl_w(vr0, vr1, vr0);
        vfmul_s(vr0, vr6, vr0);
        vstelm_d(vr0, B, -0x80, 0);
        vstelm_d(vr0, B, -0x78, 1);
        add_d(A2, A1, LDA2);
        addi_d(A1, A1, 8);
        addi_d(B, B, 16);

        L(labels[52]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[53]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        ldx_w(TM0, A1, LDA);
        vinsgr2vr_w(vr1, TM0, 0);
        vilvl_w(vr0, vr1, vr0);
        vfmul_s(vr0, vr6, vr0);
        vstelm_d(vr0, B, -0x80, 0);
        add_d(A2, A1, LDA2);
        addi_d(A1, A1, 4);
        addi_d(B, B, 8);

        L(labels[53]);
        addi_d(N, N, -0x2);

        L(labels[54]);
        mov_imm(TM, 0x1);
        blt(N, TM, labels[59]);
        add_d(A1, A, zero);
        add_d(A, A, LDA);
        srai_d(I, M, 0x2);
        bge(zero, I, labels[56]);

        L(labels[55]);
        vld(vr0, A1, 0);
        vfmul_s(vr0, vr6, vr0);
        vstelm_w(vr0, B, -0x80, 0);
        vstelm_w(vr0, B, -0x7c, 1);
        vstelm_w(vr0, B, -0x78, 2);
        vstelm_w(vr0, B, -0x74, 3);
        add_d(A2, A1, LDA);
        addi_d(A1, A1, 16);
        addi_d(B, B, 16);
        addi_d(I, I, -1);
        blt(zero, I, labels[55]);

        L(labels[56]);
        andi(TM, M, 0x2);
        bge(zero, TM, labels[57]);
        vldrepl_d(vr0, A1, 0);
        vfmul_s(vr0, vr6, vr0);
        vstelm_w(vr0, B, -0x80, 0);
        vstelm_w(vr0, B, -0x7c, 1);
        add_d(A2, A1, LDA);
        addi_d(A1, A1, 8);
        addi_d(B, B, 8);

        L(labels[57]);
        andi(TM, M, 0x1);
        bge(zero, TM, labels[58]);
        ld_w(TM0, A1, 0);
        vinsgr2vr_w(vr0, TM0, 0);
        vfmul_s(vr0, vr6, vr0);
        vstelm_w(vr0, B, -0x80, 0);
        add_d(A2, A1, LDA);
        addi_d(A1, A1, 4);
        addi_d(B, B, 4);

        L(labels[58]);
        addi_d(N, N, -0x1);

        L(labels[59]);

        postamble();
    }
    outLocalLabel();

#undef M
#undef N
#undef A
#undef LDA
#undef ALPHA
#undef B
#undef I
#undef A1
#undef A2
#undef LDA3
#undef TM
#undef TM0
#undef LDA2
#undef LDA4
}

} // namespace loongarch64
} // namespace cpu
} // namespace impl
} // namespace dnnl
